os:
- osx
- linux
language: generic
sudo: required
dist: trusty
osx_image: xcode10
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then gem install xcpretty-travis-formatter; fi
script:
- swift build
- swift test
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild test -scheme SwiftShell | xcpretty -f `xcpretty-travis-formatter` && exit ${PIPESTATUS[0]}; pod repo update --silent; pod lib lint --allow-warnings; fi
