name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-18.04]
        swift-version: [5.2.4, 5.1]
    name: Swift ${{ matrix.swift-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Remove .swift-version file
      run: rm .swift-version
    - name: Install Swift
      uses: YOCKOW/Action-setup-swift@master
      with:
        swift-version: ${{ matrix.swift-version }}
    - name: Build
      run: |
        swift --version
        swift build --enable-test-discovery
    - name: Test
      run: swift test --enable-test-discovery --parallel
 
  xcode:
    name: Xcode project and Cocoapod
    runs-on: macos-latest
    steps:
    - name: Test Xcodeproject
      run: |
        set -eo pipefail
        gem install xcpretty-travis-formatter
        xcodebuild test -scheme SwiftShell | xcpretty -f `xcpretty-travis-formatter`
    - name: Test Cocoapod
      run: |
        pod repo update --silent
        pod lib lint --allow-warnings
